{
  "openapi": "3.0.2",
  "info": {
    "title": "E-Commerce ALTA - Project 1 (Group : 2)",
    "description": "Dokumentasi API ToDoList untuk kelas ICP",
    "contact": {
      "name": "kelompok 2",
      "email": "kelompok2@aja.com"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://api.server.test/{version}",
      "variables": {
        "version": {
          "default": "v1",
          "enum": [
            "v1",
            "v2"
          ]
        }
      }
    }
  ],
  "paths": {
    "/users/login":{
      "post":{
        "summary": "Login Users",
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "required": true,
          "description": "Please Login",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "test@test.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Success Login"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name": {
                          "type": "string",
                          "example": "test"
                        },
                        "email": {
                          "type": "string",
                          "example": "test@test.com"
                        }
                      }
                    },
                    "token":{
                      "type": "object",
                      "example": "hbskbasua6t3286t87fg8ybibiesufbg9aey29f"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "Get All Users",
        "tags": [
          "Admin"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Success to get all users"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "address":{
                            "type": "string"
                          },
                          "rules_id":{
                            "type":"integer"
                          }
                        }
                      },
                      "example": [
                        {
                          "id": 1,
                          "name": "test1",
                          "email": "test1@test.com",
                          "address": "jkt brow",
                          "rules_id": 1
                        },
                        {
                          "id": 2,
                          "name": "test1",
                          "email": "test1@test.com",
                          "address": "jkt brow",
                          "rules_id": 1
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/users/register":{
      "post": {
        "summary": "Register Users",
        "tags": [
          "Users"
        ],
        "requestBody": {
          "required": true,
          "description": "Input Parameters to Register",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "test"
                  },
                  "email": {
                    "type": "string",
                    "example": "test@test.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "123"
                  },
                  "address":{
                    "type": "string",
                    "example": "surabaya"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Success to Resgister user"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name":{
                          "type": "string",
                          "example": "test"
                        },
                        "email": {
                          "type": "string",
                          "example": "test@test.com"
                        },
                        "password": {
                          "type": "string",
                          "example" : "123"
                        },
                        "address":{
                          "type": "string",
                          "example": "surabaya"
                        },
                        "rules_id":{
                          "type": "integer",
                          "example": 1
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "500":{
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/users/profile": {
      "get": {
        "summary": "Get User Profile",
        "tags": [
          "Users"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Success to get all users"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "address":{
                            "type": "string"
                          },
                          "rules_id":{
                            "type":"integer"
                          }
                        }
                      },
                      "example": [
                        {
                          "id": 1,
                          "name": "test1",
                          "email": "test1@test.com",
                          "address": "surabaya",
                          "password": "123",
                          "rules_id": 1
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "500":{
            "$ref": "#/components/responses/500"
          }
        }
      },
      "put": {
        "summary": "Update User by ID",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "User ID",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/TestListInput"
              },
              "example": {
                "name": "updated_name",
                "password": "updated_password"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/SuccessSingleResponse"
                },
                "example": {
                  "code": 1,
                  "message": "Berhasil ubah aktivitas",
                  "data": {
                    "name": "updated_name",
                    "password": "updated_password"
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "500":{
            "$ref": "#/components/responses/500"
          }
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/task"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessSingleResponse"
                },
                "example": {
                  "code": 200,
                  "message": "Success to delete Data",
                  "data": {}
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "500":{
            "$ref": "#/components/responses/500"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "task": {
        "name": "id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "integer"
        }
      }
    },
    "schemas": {
      "TestListInput": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "SuccessSingleResponse": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/TestListInput"
          }
        }
      }
    },
    "responses": {
      "400": {
        "description": "Invalid Input",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "example": 400
                },
                "message": {
                  "type": "string",
                  "example": "invalid input"
                },
                "data": {
                  "type": "object"
                }
              }
            }
          }
        }
      },
      "500": {
        "description": "Server Error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "example": 500
                },
                "message": {
                  "type": "string",
                  "example": "There are some problem in server"
                },
                "data": {
                  "type": "object"
                }
              }
             }
          }    
        }
      }
    }  
  }
}